-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."quiz_categories" add column "created_at" timestamptz
--  null default now();
